on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-slim
    permissions:
      contents: write

    steps:
      - run: |
          curl -LO https://github.com/spotiflacapp/SpotiFLAC-Mobile/archive/refs/heads/main.tar.gz
          tar -xf main.tar.gz

      - uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7.0.0
        with:
          go-version-file: SpotiFLAC-Mobile-main/go_backend/go.mod
          cache-dependency-path: SpotiFLAC-Mobile-main/go_backend/go.sum

      - uses: actions/setup-java@dd06d9cba3e5552c54d9f8ea23572deb30010f7c # v6.0.0
        with:
          distribution: temurin
          java-version: "25"
          cache-jdk: true

      - run: |
          echo "ANDROID_SDK_ROOT=$HOME/.android/sdk" >> $GITHUB_ENV

      - uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
        with:
          path: |
            $ANDROID_SDK_ROOT/platforms/android-37
            $ANDROID_SDK_ROOT/build-tools/37.0.0
            $ANDROID_SDK_ROOT/ndk/29.0.14206865
          key: platform37-build37-ndk29

      - uses: android-actions/setup-android@40fd30fb8d7440372e1316f5d1809ec01dcd3699 # v4.0.1
        with:
          cmdline-tools-version: 15859902

      - run: |
          android sdk "ndk;29.0.14206865" "platforms;android-37.0" "build-tools;37.0.0"

      - uses: subosito/flutter-action@1a449444c387b1966244ae4d4f8c696479add0b2 # v2.23.0
        with:
          channel: stable
          flutter-version-file: SpotiFLAC-Mobile-main/.fvmrc
          cache: true

      - working-directory: SpotiFLAC-Mobile-main/go_backend
        run: |
          go install golang.org/x/mobile/cmd/gomobile
          gomobile init
          mkdir -p ../android/app/libs
          gomobile bind -target=android/amd64 -androidapi 24 -o ../android/app/libs/gobackend.aar .
        env:
          CGO_ENABLED: 1

      - working-directory: SpotiFLAC-Mobile-main
        run: |
          flutter pub get
          dart run flutter_launcher_icons
          flutter build apk --release --target-platform android-x64

      - env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release create SpotiFLAC-Mobile-main ./SpotiFLAC-Mobile-main/build/app/outputs/flutter-apk/app-x86_64-release.apk --draft --repo $GITHUB_REPOSITORY
